import Head from "next/head";
import Navbar from "@/components/molecules/Navbar";
import Container from "@/components/atoms/Container";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
import Header from "@/components/atoms/Header";

export default function Home() {
  // const { user } = useSelector((state) => state.auth);
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Navbar />
          <Header title="Dashboard" />
        </Container>
      </main>
    </>
  );
}
